// Auto-generated by scripts during biome refactor.

import alpineMire from "./authored/alpine_mire.js";
import alpineSteppe from "./authored/alpine_steppe.js";
import alpineSummit from "./authored/alpine_summit.js";
import alpineTundra from "./authored/alpine_tundra.js";
import aridSummit from "./authored/arid_summit.js";
import badlands from "./authored/badlands.js";
import barrenHighlands from "./authored/barren_highlands.js";
import cloudforestHot from "./authored/cloudforest_hot.js";
import cloudforestTemperate from "./authored/cloudforest_temperate.js";
import coastalTundra from "./authored/coastal_tundra.js";
import coldOcean from "./authored/cold_ocean.js";
import coralReef from "./authored/coral_reef.js";
import deepColdOcean from "./authored/deep_cold_ocean.js";
import deepOcean from "./authored/deep_ocean.js";
import deepTropicalOcean from "./authored/deep_tropical_ocean.js";
import desert from "./authored/desert.js";
import forest from "./authored/forest.js";
import frostPeak from "./authored/frost_peak.js";
import glacialSummit from "./authored/glacial_summit.js";
import glacier from "./authored/glacier.js";
import icefield from "./authored/icefield.js";
import icySummit from "./authored/icy_summit.js";
import kelpForestCold from "./authored/kelp_forest_cold.js";
import kelpForest from "./authored/kelp_forest.js";
import kelpShoreCold from "./authored/kelp_shore_cold.js";
import kelpShore from "./authored/kelp_shore.js";
import mangrove from "./authored/mangrove.js";
import marsh from "./authored/marsh.js";
import meadow from "./authored/meadow.js";
import mire from "./authored/mire.js";
import monsoonForest from "./authored/monsoon_forest.js";
import montaneWoodland from "./authored/montane_woodland.js";
import montane from "./authored/montane.js";
import mountainGrassland from "./authored/mountain_grassland.js";
import mudflat from "./authored/mudflat.js";
import muskeg from "./authored/muskeg.js";
import ocean from "./authored/ocean.js";
import paramo from "./authored/paramo.js";
import polarDesert from "./authored/polar_desert.js";
import polarScree from "./authored/polar_scree.js";
import rainforestHot from "./authored/rainforest_hot.js";
import rainforestTemperate from "./authored/rainforest_temperate.js";
import rockyMountains from "./authored/rocky_mountains.js";
import rockyShore from "./authored/rocky_shore.js";
import rockydesert from "./authored/rockydesert.js";
import saltMarsh from "./authored/salt_marsh.js";
import saltflat from "./authored/saltflat.js";
import savannaMesic from "./authored/savanna_mesic.js";
import savanna from "./authored/savanna.js";
import scrubland from "./authored/scrubland.js";
import seagrassMeadow from "./authored/seagrass_meadow.js";
import shrubland from "./authored/shrubland.js";
import steppe from "./authored/steppe.js";
import subalpine from "./authored/subalpine.js";
import taiga from "./authored/taiga.js";
import thornForest from "./authored/thorn_forest.js";
import tropicalLagoon from "./authored/tropical_lagoon.js";
import tropicalOcean from "./authored/tropical_ocean.js";
import tundraMesic from "./authored/tundra_mesic.js";
import tundra from "./authored/tundra.js";
import wetlandHydric from "./authored/wetland_hydric.js";
import wetland from "./authored/wetland.js";
import woodlandCold from "./authored/woodland_cold.js";
import woodlandTemperate from "./authored/woodland_temperate.js";

import genBadlandsMountains from "./generated/badlands_mountains.js";
import genDesertMountains from "./generated/desert_mountains.js";
import genForestMountains from "./generated/forest_mountains.js";
import genGlacierMountains from "./generated/glacier_mountains.js";
import genIcefieldMountains from "./generated/icefield_mountains.js";
import genJaggedAlpineMire from "./generated/jagged_alpine_mire.js";
import genJaggedAlpineSteppe from "./generated/jagged_alpine_steppe.js";
import genJaggedAlpineSummit from "./generated/jagged_alpine_summit.js";
import genJaggedAlpineTundra from "./generated/jagged_alpine_tundra.js";
import genJaggedAridSummit from "./generated/jagged_arid_summit.js";
import genJaggedBadlandsMountains from "./generated/jagged_badlands_mountains.js";
import genJaggedBadlands from "./generated/jagged_badlands.js";
import genJaggedBarrenHighlands from "./generated/jagged_barren_highlands.js";
import genJaggedCloudforestHot from "./generated/jagged_cloudforest_hot.js";
import genJaggedCloudforestTemperate from "./generated/jagged_cloudforest_temperate.js";
import genJaggedDesert from "./generated/jagged_desert.js";
import genJaggedFrostPeak from "./generated/jagged_frost_peak.js";
import genJaggedGlacialSummit from "./generated/jagged_glacial_summit.js";
import genJaggedGlacierMountains from "./generated/jagged_glacier_mountains.js";
import genJaggedGlacier from "./generated/jagged_glacier.js";
import genJaggedIcefield from "./generated/jagged_icefield.js";
import genJaggedIcySummit from "./generated/jagged_icy_summit.js";
import genJaggedMontane from "./generated/jagged_montane.js";
import genJaggedMountainGrassland from "./generated/jagged_mountain_grassland.js";
import genJaggedParamo from "./generated/jagged_paramo.js";
import genJaggedPolarDesert from "./generated/jagged_polar_desert.js";
import genJaggedPolarScree from "./generated/jagged_polar_scree.js";
import genJaggedRockyMountains from "./generated/jagged_rocky_mountains.js";
import genJaggedRockydesert from "./generated/jagged_rockydesert.js";
import genJaggedSaltflat from "./generated/jagged_saltflat.js";
import genJaggedScrubland from "./generated/jagged_scrubland.js";
import genJaggedThornForest from "./generated/jagged_thorn_forest.js";
import genMarshMountains from "./generated/marsh_mountains.js";
import genMeadowMountains from "./generated/meadow_mountains.js";
import genMireMountains from "./generated/mire_mountains.js";
import genMonsoonForestMountains from "./generated/monsoon_forest_mountains.js";
import genMuskegMountains from "./generated/muskeg_mountains.js";
import genPolarDesertMountains from "./generated/polar_desert_mountains.js";
import genRainforestHotMountains from "./generated/rainforest_hot_mountains.js";
import genRainforestTemperateMountains from "./generated/rainforest_temperate_mountains.js";
import genSaltflatMountains from "./generated/saltflat_mountains.js";
import genSavannaMesicMountains from "./generated/savanna_mesic_mountains.js";
import genSavannaMountains from "./generated/savanna_mountains.js";
import genScrublandMountains from "./generated/scrubland_mountains.js";
import genShrublandMountains from "./generated/shrubland_mountains.js";
import genSmoothAlpineMire from "./generated/smooth_alpine_mire.js";
import genSmoothAlpineSteppe from "./generated/smooth_alpine_steppe.js";
import genSmoothAlpineSummit from "./generated/smooth_alpine_summit.js";
import genSmoothAlpineTundra from "./generated/smooth_alpine_tundra.js";
import genSmoothAridSummit from "./generated/smooth_arid_summit.js";
import genSmoothBadlandsMountains from "./generated/smooth_badlands_mountains.js";
import genSmoothBadlands from "./generated/smooth_badlands.js";
import genSmoothBarrenHighlands from "./generated/smooth_barren_highlands.js";
import genSmoothCloudforestHot from "./generated/smooth_cloudforest_hot.js";
import genSmoothCloudforestTemperate from "./generated/smooth_cloudforest_temperate.js";
import genSmoothDesert from "./generated/smooth_desert.js";
import genSmoothFrostPeak from "./generated/smooth_frost_peak.js";
import genSmoothGlacialSummit from "./generated/smooth_glacial_summit.js";
import genSmoothGlacierMountains from "./generated/smooth_glacier_mountains.js";
import genSmoothGlacier from "./generated/smooth_glacier.js";
import genSmoothIcefield from "./generated/smooth_icefield.js";
import genSmoothIcySummit from "./generated/smooth_icy_summit.js";
import genSmoothMontane from "./generated/smooth_montane.js";
import genSmoothMountainGrassland from "./generated/smooth_mountain_grassland.js";
import genSmoothParamo from "./generated/smooth_paramo.js";
import genSmoothPolarDesert from "./generated/smooth_polar_desert.js";
import genSmoothPolarScree from "./generated/smooth_polar_scree.js";
import genSmoothRockyMountains from "./generated/smooth_rocky_mountains.js";
import genSmoothRockydesert from "./generated/smooth_rockydesert.js";
import genSmoothSaltflat from "./generated/smooth_saltflat.js";
import genSmoothScrubland from "./generated/smooth_scrubland.js";
import genSmoothThornForest from "./generated/smooth_thorn_forest.js";
import genSteppeMountains from "./generated/steppe_mountains.js";
import genTaigaMountains from "./generated/taiga_mountains.js";
import genThornForestMountains from "./generated/thorn_forest_mountains.js";
import genTundraMesicMountains from "./generated/tundra_mesic_mountains.js";
import genTundraMountains from "./generated/tundra_mountains.js";
import genWetlandHydricMountains from "./generated/wetland_hydric_mountains.js";
import genWetlandMountains from "./generated/wetland_mountains.js";
import genWoodlandColdMountains from "./generated/woodland_cold_mountains.js";
import genWoodlandTemperateMountains from "./generated/woodland_temperate_mountains.js";

export const AUTHORED_BIOME_DEFINITIONS = Object.freeze([
  alpineMire,
  alpineSteppe,
  alpineSummit,
  alpineTundra,
  aridSummit,
  badlands,
  barrenHighlands,
  cloudforestHot,
  cloudforestTemperate,
  coastalTundra,
  coldOcean,
  coralReef,
  deepColdOcean,
  deepOcean,
  deepTropicalOcean,
  desert,
  forest,
  frostPeak,
  glacialSummit,
  glacier,
  icefield,
  icySummit,
  kelpForestCold,
  kelpForest,
  kelpShoreCold,
  kelpShore,
  mangrove,
  marsh,
  meadow,
  mire,
  monsoonForest,
  montaneWoodland,
  montane,
  mountainGrassland,
  mudflat,
  muskeg,
  ocean,
  paramo,
  polarDesert,
  polarScree,
  rainforestHot,
  rainforestTemperate,
  rockyMountains,
  rockyShore,
  rockydesert,
  saltMarsh,
  saltflat,
  savannaMesic,
  savanna,
  scrubland,
  seagrassMeadow,
  shrubland,
  steppe,
  subalpine,
  taiga,
  thornForest,
  tropicalLagoon,
  tropicalOcean,
  tundraMesic,
  tundra,
  wetlandHydric,
  wetland,
  woodlandCold,
  woodlandTemperate,
]);

export const GENERATED_BIOME_DEFINITIONS = Object.freeze([
  genBadlandsMountains,
  genDesertMountains,
  genForestMountains,
  genGlacierMountains,
  genIcefieldMountains,
  genJaggedAlpineMire,
  genJaggedAlpineSteppe,
  genJaggedAlpineSummit,
  genJaggedAlpineTundra,
  genJaggedAridSummit,
  genJaggedBadlandsMountains,
  genJaggedBadlands,
  genJaggedBarrenHighlands,
  genJaggedCloudforestHot,
  genJaggedCloudforestTemperate,
  genJaggedDesert,
  genJaggedFrostPeak,
  genJaggedGlacialSummit,
  genJaggedGlacierMountains,
  genJaggedGlacier,
  genJaggedIcefield,
  genJaggedIcySummit,
  genJaggedMontane,
  genJaggedMountainGrassland,
  genJaggedParamo,
  genJaggedPolarDesert,
  genJaggedPolarScree,
  genJaggedRockyMountains,
  genJaggedRockydesert,
  genJaggedSaltflat,
  genJaggedScrubland,
  genJaggedThornForest,
  genMarshMountains,
  genMeadowMountains,
  genMireMountains,
  genMonsoonForestMountains,
  genMuskegMountains,
  genPolarDesertMountains,
  genRainforestHotMountains,
  genRainforestTemperateMountains,
  genSaltflatMountains,
  genSavannaMesicMountains,
  genSavannaMountains,
  genScrublandMountains,
  genShrublandMountains,
  genSmoothAlpineMire,
  genSmoothAlpineSteppe,
  genSmoothAlpineSummit,
  genSmoothAlpineTundra,
  genSmoothAridSummit,
  genSmoothBadlandsMountains,
  genSmoothBadlands,
  genSmoothBarrenHighlands,
  genSmoothCloudforestHot,
  genSmoothCloudforestTemperate,
  genSmoothDesert,
  genSmoothFrostPeak,
  genSmoothGlacialSummit,
  genSmoothGlacierMountains,
  genSmoothGlacier,
  genSmoothIcefield,
  genSmoothIcySummit,
  genSmoothMontane,
  genSmoothMountainGrassland,
  genSmoothParamo,
  genSmoothPolarDesert,
  genSmoothPolarScree,
  genSmoothRockyMountains,
  genSmoothRockydesert,
  genSmoothSaltflat,
  genSmoothScrubland,
  genSmoothThornForest,
  genSteppeMountains,
  genTaigaMountains,
  genThornForestMountains,
  genTundraMesicMountains,
  genTundraMountains,
  genWetlandHydricMountains,
  genWetlandMountains,
  genWoodlandColdMountains,
  genWoodlandTemperateMountains,
]);

export const ALL_BIOME_DEFINITIONS = Object.freeze([
  ...AUTHORED_BIOME_DEFINITIONS,
  ...GENERATED_BIOME_DEFINITIONS,
]);
