// Auto-generated by scripts during biome refactor.

import alpineMire from "./authored/alpine_mire.js";
import alpineSteppe from "./authored/alpine_steppe.js";
import alpineTundra from "./authored/alpine_tundra.js";
import badlands from "./authored/badlands.js";
import cloudforestHot from "./authored/cloudforest_hot.js";
import cloudforestTemperate from "./authored/cloudforest_temperate.js";
import desert from "./authored/desert.js";
import forest from "./authored/forest.js";
import glacier from "./authored/glacier.js";
import icefield from "./authored/icefield.js";
import marsh from "./authored/marsh.js";
import meadow from "./authored/meadow.js";
import mire from "./authored/mire.js";
import monsoonForest from "./authored/monsoon_forest.js";
import montane from "./authored/montane.js";
import montaneWoodland from "./authored/montane_woodland.js";
import muskeg from "./authored/muskeg.js";
import polarDesert from "./authored/polar_desert.js";
import rainforestHot from "./authored/rainforest_hot.js";
import rainforestTemperate from "./authored/rainforest_temperate.js";
import rockyMountains from "./authored/rocky_mountains.js";
import rockydesert from "./authored/rockydesert.js";
import saltflat from "./authored/saltflat.js";
import savanna from "./authored/savanna.js";
import savannaMesic from "./authored/savanna_mesic.js";
import scrubland from "./authored/scrubland.js";
import shrubland from "./authored/shrubland.js";
import steppe from "./authored/steppe.js";
import subalpine from "./authored/subalpine.js";
import taiga from "./authored/taiga.js";
import thornForest from "./authored/thorn_forest.js";
import tundra from "./authored/tundra.js";
import tundraMesic from "./authored/tundra_mesic.js";
import wetland from "./authored/wetland.js";
import wetlandHydric from "./authored/wetland_hydric.js";
import woodlandCold from "./authored/woodland_cold.js";
import woodlandTemperate from "./authored/woodland_temperate.js";

import genBadlandsMountains from "./generated/badlands_mountains.js";
import genDesertMountains from "./generated/desert_mountains.js";
import genForestMountains from "./generated/forest_mountains.js";
import genGlacierMountains from "./generated/glacier_mountains.js";
import genIcefieldMountains from "./generated/icefield_mountains.js";
import genJaggedAlpineMire from "./generated/jagged_alpine_mire.js";
import genJaggedAlpineSteppe from "./generated/jagged_alpine_steppe.js";
import genJaggedAlpineTundra from "./generated/jagged_alpine_tundra.js";
import genJaggedBadlands from "./generated/jagged_badlands.js";
import genJaggedBadlandsMountains from "./generated/jagged_badlands_mountains.js";
import genJaggedCloudforestHot from "./generated/jagged_cloudforest_hot.js";
import genJaggedCloudforestTemperate from "./generated/jagged_cloudforest_temperate.js";
import genJaggedDesert from "./generated/jagged_desert.js";
import genJaggedGlacier from "./generated/jagged_glacier.js";
import genJaggedGlacierMountains from "./generated/jagged_glacier_mountains.js";
import genJaggedIcefield from "./generated/jagged_icefield.js";
import genJaggedMontane from "./generated/jagged_montane.js";
import genJaggedPolarDesert from "./generated/jagged_polar_desert.js";
import genJaggedRockyMountains from "./generated/jagged_rocky_mountains.js";
import genJaggedRockydesert from "./generated/jagged_rockydesert.js";
import genJaggedSaltflat from "./generated/jagged_saltflat.js";
import genJaggedScrubland from "./generated/jagged_scrubland.js";
import genJaggedThornForest from "./generated/jagged_thorn_forest.js";
import genMarshMountains from "./generated/marsh_mountains.js";
import genMeadowMountains from "./generated/meadow_mountains.js";
import genMireMountains from "./generated/mire_mountains.js";
import genMonsoonForestMountains from "./generated/monsoon_forest_mountains.js";
import genMuskegMountains from "./generated/muskeg_mountains.js";
import genPolarDesertMountains from "./generated/polar_desert_mountains.js";
import genRainforestHotMountains from "./generated/rainforest_hot_mountains.js";
import genRainforestTemperateMountains from "./generated/rainforest_temperate_mountains.js";
import genSaltflatMountains from "./generated/saltflat_mountains.js";
import genSavannaMesicMountains from "./generated/savanna_mesic_mountains.js";
import genSavannaMountains from "./generated/savanna_mountains.js";
import genScrublandMountains from "./generated/scrubland_mountains.js";
import genShrublandMountains from "./generated/shrubland_mountains.js";
import genSmoothAlpineMire from "./generated/smooth_alpine_mire.js";
import genSmoothAlpineSteppe from "./generated/smooth_alpine_steppe.js";
import genSmoothAlpineTundra from "./generated/smooth_alpine_tundra.js";
import genSmoothBadlands from "./generated/smooth_badlands.js";
import genSmoothBadlandsMountains from "./generated/smooth_badlands_mountains.js";
import genSmoothCloudforestHot from "./generated/smooth_cloudforest_hot.js";
import genSmoothCloudforestTemperate from "./generated/smooth_cloudforest_temperate.js";
import genSmoothDesert from "./generated/smooth_desert.js";
import genSmoothGlacier from "./generated/smooth_glacier.js";
import genSmoothGlacierMountains from "./generated/smooth_glacier_mountains.js";
import genSmoothIcefield from "./generated/smooth_icefield.js";
import genSmoothMontane from "./generated/smooth_montane.js";
import genSmoothPolarDesert from "./generated/smooth_polar_desert.js";
import genSmoothRockyMountains from "./generated/smooth_rocky_mountains.js";
import genSmoothRockydesert from "./generated/smooth_rockydesert.js";
import genSmoothSaltflat from "./generated/smooth_saltflat.js";
import genSmoothScrubland from "./generated/smooth_scrubland.js";
import genSmoothThornForest from "./generated/smooth_thorn_forest.js";
import genSteppeMountains from "./generated/steppe_mountains.js";
import genTaigaMountains from "./generated/taiga_mountains.js";
import genThornForestMountains from "./generated/thorn_forest_mountains.js";
import genTundraMesicMountains from "./generated/tundra_mesic_mountains.js";
import genTundraMountains from "./generated/tundra_mountains.js";
import genWetlandHydricMountains from "./generated/wetland_hydric_mountains.js";
import genWetlandMountains from "./generated/wetland_mountains.js";
import genWoodlandColdMountains from "./generated/woodland_cold_mountains.js";
import genWoodlandTemperateMountains from "./generated/woodland_temperate_mountains.js";

export const AUTHORED_BIOME_DEFINITIONS = Object.freeze([
  alpineMire,
  alpineSteppe,
  alpineTundra,
  badlands,
  cloudforestHot,
  cloudforestTemperate,
  desert,
  forest,
  glacier,
  icefield,
  marsh,
  meadow,
  mire,
  monsoonForest,
  montane,
  montaneWoodland,
  muskeg,
  polarDesert,
  rainforestHot,
  rainforestTemperate,
  rockyMountains,
  rockydesert,
  saltflat,
  savanna,
  savannaMesic,
  scrubland,
  shrubland,
  steppe,
  subalpine,
  taiga,
  thornForest,
  tundra,
  tundraMesic,
  wetland,
  wetlandHydric,
  woodlandCold,
  woodlandTemperate,
]);

export const GENERATED_BIOME_DEFINITIONS = Object.freeze([
  genBadlandsMountains,
  genDesertMountains,
  genForestMountains,
  genGlacierMountains,
  genIcefieldMountains,
  genJaggedAlpineMire,
  genJaggedAlpineSteppe,
  genJaggedAlpineTundra,
  genJaggedBadlands,
  genJaggedBadlandsMountains,
  genJaggedCloudforestHot,
  genJaggedCloudforestTemperate,
  genJaggedDesert,
  genJaggedGlacier,
  genJaggedGlacierMountains,
  genJaggedIcefield,
  genJaggedMontane,
  genJaggedPolarDesert,
  genJaggedRockyMountains,
  genJaggedRockydesert,
  genJaggedSaltflat,
  genJaggedScrubland,
  genJaggedThornForest,
  genMarshMountains,
  genMeadowMountains,
  genMireMountains,
  genMonsoonForestMountains,
  genMuskegMountains,
  genPolarDesertMountains,
  genRainforestHotMountains,
  genRainforestTemperateMountains,
  genSaltflatMountains,
  genSavannaMesicMountains,
  genSavannaMountains,
  genScrublandMountains,
  genShrublandMountains,
  genSmoothAlpineMire,
  genSmoothAlpineSteppe,
  genSmoothAlpineTundra,
  genSmoothBadlands,
  genSmoothBadlandsMountains,
  genSmoothCloudforestHot,
  genSmoothCloudforestTemperate,
  genSmoothDesert,
  genSmoothGlacier,
  genSmoothGlacierMountains,
  genSmoothIcefield,
  genSmoothMontane,
  genSmoothPolarDesert,
  genSmoothRockyMountains,
  genSmoothRockydesert,
  genSmoothSaltflat,
  genSmoothScrubland,
  genSmoothThornForest,
  genSteppeMountains,
  genTaigaMountains,
  genThornForestMountains,
  genTundraMesicMountains,
  genTundraMountains,
  genWetlandHydricMountains,
  genWetlandMountains,
  genWoodlandColdMountains,
  genWoodlandTemperateMountains,
]);

export const ALL_BIOME_DEFINITIONS = Object.freeze([
  ...AUTHORED_BIOME_DEFINITIONS,
  ...GENERATED_BIOME_DEFINITIONS,
]);
